projects:
  app:
    schemaPath: server/controllers/schema.graphql
    extensions:
      endpoints:
        default: http://localhost:4466
  prisma:
    schemaPath: server/controllers/generated/prisma.graphql
    extensions:
      prisma: prisma.yml